grails-app/domain/com/bits/sart/model/Research.groovy
package com.bits.sart.model

class Research extends AbstractDomain {

	ResearchCategory researchCategory
	
	Client client
	
	String title
	
	String description
	
	String sampleSize
	
	String responsibility
	
	Methodology methodology
	String methodologyDescription
	
	Duration duration
	
	Double budget
	
	String softwareUsed					//{can be changed to List<SoftwareUsed>}
	
	SartUser projectManager				//{must be a registered user}
	
	String researchReferences					//{needs description}
	
	String externalCollaborators
	
	String remark
	
	String lessonsLearned				//{can be LessonsLearned lessonsLearned}
	
/*	List<City> geographicalCoverage
	
	List<Researcher> researchers
	
	List<Attachment> attachments*/
	
	Date dateCreated
	Date lastUpdated
	User createdByUser
	User updatedByUser
	
	static hasMany = [geographicalCoverage : City,
					  researchers: Researcher,
					  attachments: Attachment]
	
//	static searchable = [ except: ['version', 'dateCreated', 'lastUpdated'] ]
	
	static constraints = {

        researchCategory nullable:false
        client nullable:false
        title blank: false, unique: true
        description nullable:false
        projectManager nullable:false
        sampleSize nullable:false
        responsibility nullable:false
        methodology nullable:false
        methodologyDescription nullable:false
        duration nullable:false
        budget nullable:true
        geographicalCoverage nullable:false
        researchers nullable:false
        attachments nullable:false
        softwareUsed nullable:false
        researchReferences nullable:true
        externalCollaborators nullable:true
       	remark nullable:true
		lessonsLearned nullable:true

		createdByUser nullable:true
		updatedByUser nullable:true
	}

}

grails-app/controllers/com/bits/sart/model/DurationController.groovy
package com.bits.sart.model


import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class DurationController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Duration.list(params), model: [durationInstanceCount: Duration.count()]
    }

    def show(Duration durationInstance) {
        respond durationInstance
    }

    def create() {
        respond new Duration(params)
    }

    @Transactional
    def save(Duration durationInstance) {
        if (durationInstance == null) {
            notFound()
            return
        }

        if (durationInstance.hasErrors()) {
            respond durationInstance.errors, view: 'create'
            return
        }

        durationInstance.save flush: true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'durationInstance.label', default: 'Duration'), durationInstance.id])
                redirect durationInstance
            }
            '*' { respond durationInstance, [status: CREATED] }
        }
    }

    def edit(Duration durationInstance) {
        respond durationInstance
    }

    @Transactional
    def update(Duration durationInstance) {
        if (durationInstance == null) {
            notFound()
            return
        }

        if (durationInstance.hasErrors()) {
            respond durationInstance.errors, view: 'edit'
            return
        }

        durationInstance.save flush: true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Duration.label', default: 'Duration'), durationInstance.id])
                redirect durationInstance
            }
            '*' { respond durationInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Duration durationInstance) {

        if (durationInstance == null) {
            notFound()
            return
        }

        durationInstance.delete flush: true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Duration.label', default: 'Duration'), durationInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'durationInstance.label', default: 'Duration'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/com/bits/sart/model/ResearchController.groovy
package com.bits.sart.model

import javax.swing.text.View

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class ResearchController {

    def researchService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Research.list(params), model: [researchInstanceCount: Research.count()]
    }

    def show(Research researchInstance) {
        respond researchInstance
    }

    def create() {
        respond new Research(params)
    }

    @Transactional
    def save(Research researchInstance) {
        if (researchInstance == null) {
            notFound()
            return
        }

        if (researchInstance.hasErrors()) {
            respond researchInstance.errors, view: 'create'
            return
        }

        researchInstance.save flush: true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'research.label', default: 'Research'), researchInstance.id])
                redirect researchInstance
            }
            '*' { respond researchInstance, [status: CREATED] }
        }
    }

    def edit(Research researchInstance) {
        respond researchInstance
    }

    @Transactional
    def update(Research researchInstance) {
        if (researchInstance == null) {
            notFound()
            return
        }

        if (researchInstance.hasErrors()) {
            respond researchInstance.errors, view: 'edit'
            return
        }

        researchInstance.save flush: true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'research.label', default: 'Research'), researchInstance.id])
                redirect researchInstance
            }
            '*' { respond researchInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Research researchInstance) {

        if (researchInstance == null) {
            notFound()
            return
        }

        researchInstance.delete flush: true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'research.label', default: 'Research'), researchInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'research.label', default: 'Research'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }

    def search() {

        params.max = Math.min(params.max ? params.int('max') : 10, 50)

        List<Research> searchResults = researchService.getListOfResearches(params.researchTitle, ResearchCategory.findByName(params.researchCategory))

        if(null != searchResults) {

            flash.message = message(code: 'research.search.success.result', args: [searchResults.size()])
            render(view: '/research/search', model: [searchResults : searchResults, researchInstanceCount: searchResults.size()])

        } else {

            flash.message = message(code: 'research.search.failed.result', default: 'Sorry, no research found')
            render(view: '/research/search', model: [searchResults : [], researchInstanceCount: 0])
        }
    }

    def addClient() {
        render(template:'addClient', model:[new Client(params)])
    }

    def saveClient() {

        Client client = researchService.saveClient(params.clientName, params.street, params.woreda, params.phoneNumber, params.cityName)

        if(null != client) {

            flash.message = message(code: 'research.saveClient.success.result')
            render(view: '/research/create')
        } else {

            flash.message = message(code: 'research.search.failed.result', default: 'Sorry, no research found')
            render(view: '/research/create')
        }

    }
}

grails-app/views/research/_addClient.gsp
<%@ page import="com.bits.sart.model.Client" %>
<%@ page import="com.bits.sart.model.Address" %>

<div class ="clientInformation">
    <div class="clientName">
        <label for="clientName">
            <g:message code="client.name.label" default="Name" />
        </label>
        <g:textField name="clientName"/>
    </div>

    <div class="street required">
        <label for="street">
            <g:message code="address.street.label" default="Street" />
            <span class="required-indicator">*</span>
        </label>
        <g:textField name="street" maxlength="100" required=""/>
    </div>

    <div class="woreda ">
        <label for="woreda">
            <g:message code="address.woreda.label" default="Woreda" />
        </label>
        <g:textField name="woreda" />
    </div>

    <div class="phoneNumber">
        <label for="phoneNumber">
            <g:message code="address.phoneNumber.label" default="Phone Number" />

        </label>
        <g:textField name="phoneNumber" />
    </div>

    <div class="city">
        <label for="city">
            <g:message code="address.city.label" default="City" />
        </label>
        <g:select id="city" name="city.id" from="${com.bits.sart.model.City.list()}" optionKey="id" optionValue="name" class="many-to-one" noSelection="['null': '']"/>
    </div>
</div>

grails-app/views/research/_form.gsp
<%@ page import="com.bits.sart.model.Research" %>

<div class="fieldcontain ${hasErrors(bean: researchInstance, field: 'researchCategory', 'error')} required">
	<label for="researchCategory">
		<g:message code="research.researchCategory.label" default="Research Category" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="researchCategory" name="researchCategory.id" from="${com.bits.sart.model.ResearchCategory.list()}" optionKey="id" optionValue="name" required="" value="${researchInstance?.researchCategory?.name}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: researchInstance, field: 'client', 'error')} required">
    <label for="client">
        <g:message code="research.client.label" default="Client" />
        <span class="required-indicator">*</span>
    </label>
    <g:select id="client" name="client.id" from="${com.bits.sart.model.Client.list()}" optionKey="id" optionValue="name" required="" value="${researchInstance?.client?.name}" class="many-to-one"/>

    <div class="newClientForm"></div>
    <form method="post">
        <input type="button" value="Add Client" onclick="addClientTemplate();">
    </form>
</div>

%{--<div class ="clientInformation">
    <g:render template="addClient" />
</div>--}%



%{--
<div class ="clientInformation">
    <g:submitButton name="addClient" onclick="showAddClient();">
        <g:message code="research.add.client.label" default="Add Client" />
    </g:submitButton>
</div>

        <g:remoteLink action="addClient" update="addClientInResearchPage" onLoading="showSpinner(true);" onComplete="showSpinner(false);">
            <g:message code="research.add.client.label" default="Add Client" />
        </g:remoteLink>
        <g:render template="addClient" />
        <div id="addClientInResearchPage">
        </div>
--}%



<div class="fieldcontain ${hasErrors(bean: researchInstance, field: 'title', 'error')} required">
	<label for="title">
		<g:message code="research.title.label" default="Title" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="title" required="" value="${researchInstance?.title}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: researchInstance, field: 'description', 'error')} ">
	<label for="description">
		<g:message code="research.description.label" default="Description" />
		
	</label>
	<g:textField name="description" value="${researchInstance?.description}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: researchInstance, field: 'projectManager', 'error')} required">
	<label for="projectManager">
		<g:message code="research.projectManager.label" default="Project Manager" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="projectManager" name="projectManager.id" from="${com.bits.sart.model.SartUser.list()}" optionKey="id" optionValue="firstName" required="" value="${researchInstance?.projectManager?.firstName + " " + researchInstance?.projectManager?.lastName}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: researchInstance, field: 'sampleSize', 'error')} ">
	<label for="sampleSize">
		<g:message code="research.sampleSize.label" default="Sample Size" />
		
	</label>
	<g:textField name="sampleSize" value="${researchInstance?.sampleSize}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: researchInstance, field: 'responsibility', 'error')} ">
	<label for="responsibility">
		<g:message code="research.responsibility.label" default="Responsibility" />
		
	</label>
	<g:textField name="responsibility" value="${researchInstance?.responsibility}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: researchInstance, field: 'methodology', 'error')} required">
	<label for="methodology">
		<g:message code="research.methodology.label" default="Methodology" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="methodology" name="methodology.id" from="${com.bits.sart.model.Methodology.list()}" optionKey="id" optionValue="name" required="" value="${researchInstance?.methodology?.name}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: researchInstance, field: 'methodologyDescription', 'error')} ">
	<label for="methodologyDescription">
		<g:message code="research.methodologyDescription.label" default="Methodology Description" />
		
	</label>
	<g:textField name="methodologyDescription" value="${researchInstance?.methodologyDescription}"/>
</div>

%{--Duration--}%

    <div class="fieldcontain ${hasErrors(bean: researchInstance.duration, field: 'startDate', 'error')} required">
        <label for="startDate">
            <g:message code="duration.startDate.label" default="Start Date" />
            <span class="required-indicator">*</span>
        </label>
        <g:datePicker name="startDate" precision="day"  value="${researchInstance.duration?.startDate}"  />
    </div>

    <div class="fieldcontain ${hasErrors(bean: researchInstance.duration, field: 'endDate', 'error')} required">
        <label for="endDate">
            <g:message code="duration.endDate.label" default="End Date" />
            <span class="required-indicator">*</span>
        </label>
        <g:datePicker name="endDate" precision="day"  value="${researchInstance.duration?.endDate}"  />
    </div>

%{--End of Duration--}%

<div class="fieldcontain ${hasErrors(bean: researchInstance, field: 'budget', 'error')} ">
	<label for="budget">
		<g:message code="research.budget.label" default="Budget" />
		
	</label>
	<g:field type="" name="budget" value="${fieldValue(bean: researchInstance, field: 'budget')}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: researchInstance, field: 'geographicalCoverage', 'error')} required">
	<label for="geographicalCoverage">
		<g:message code="research.geographicalCoverage.label" default="Geographical Coverage" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="geographicalCoverage" from="${com.bits.sart.model.City.list()}" multiple="multiple" optionKey="id" optionValue="name" size="5" required="" value="${researchInstance?.geographicalCoverage*.name}" class="many-to-many"/>
</div>

<div class="fieldcontain ${hasErrors(bean: researchInstance, field: 'researchers', 'error')} required">
	<label for="researchers">
		<g:message code="research.researchers.label" default="Researchers" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="researchers" from="${com.bits.sart.model.Researcher.list()}" multiple="multiple" optionKey="id" optionValue="sartUser" size="5" required="" value="${researchInstance?.researchers?.sartUser?.firstName}" class="many-to-many"/>
</div>

<div class="fieldcontain ${hasErrors(bean: researchInstance?.attachments, field: 'description', 'error')} ">
    <label for="description">
        <g:message code="attachment.description.label" default="Description" />

    </label>
    <g:textField name="description" value="${researchInstance?.attachments?.description}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: researchInstance?.attachments, field: 'fileName', 'error')} required">
    <label for="fileName">
        <g:message code="attachment.fileName.label" default="File Name" />
        <span class="required-indicator">*</span>
    </label>
    <input type="file" id="fileName" name="fileName" />
</div>

<div class="fieldcontain ${hasErrors(bean: researchInstance?.attachments, field: 'type', 'error')} ">
    <label for="type">
        <g:message code="attachment.type.label" default="Type" />

    </label>
    <g:textField name="type" value="${researchInstance?.attachments?.type}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: researchInstance, field: 'softwareUsed', 'error')} ">
	<label for="softwareUsed">
		<g:message code="research.softwareUsed.label" default="Software Used" />
		
	</label>
	<g:textField name="softwareUsed" value="${researchInstance?.softwareUsed}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: researchInstance, field: 'researchReferences', 'error')} ">
	<label for="researchReferences">
		<g:message code="research.researchReferences.label" default="Research References" />
		
	</label>
	<g:textField name="researchReferences" value="${researchInstance?.researchReferences}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: researchInstance, field: 'externalCollaborators', 'error')} ">
	<label for="externalCollaborators">
		<g:message code="research.externalCollaborators.label" default="External Collaborators" />
		
	</label>
	<g:textField name="externalCollaborators" value="${researchInstance?.externalCollaborators}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: researchInstance, field: 'remark', 'error')} ">
	<label for="remark">
		<g:message code="research.remark.label" default="Remark" />
		
	</label>
	<g:textField name="remark" value="${researchInstance?.remark}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: researchInstance, field: 'lessonsLearned', 'error')} ">
	<label for="lessonsLearned">
		<g:message code="research.lessonsLearned.label" default="Lessons Learned" />
		
	</label>
	<g:textField name="lessonsLearned" value="${researchInstance?.lessonsLearned}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: researchInstance, field: 'createdByUser', 'error')} ">
	<label for="createdByUser">
		<g:message code="research.createdByUser.label" default="Created By" />
		
	</label>
	<g:select id="createdByUser" name="createdByUser.id" from="${com.bits.sart.model.User.list()}" optionKey="id" optionValue="username" value="${researchInstance?.createdByUser?.username}" class="many-to-one" noSelection="['null': '']"/>
</div>

<div class="fieldcontain ${hasErrors(bean: researchInstance, field: 'updatedByUser', 'error')} ">
	<label for="updatedByUser">
		<g:message code="research.updatedByUser.label" default="Updated By" />
		
	</label>
	<g:select id="updatedByUser" name="updatedByUser.id" from="${com.bits.sart.model.User.list()}" optionKey="id" optionValue="username" value="${researchInstance?.updatedByUser?.username}" class="many-to-one" noSelection="['null': '']"/>
</div>

grails-app/views/research/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'research.label', default: 'Research')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-research" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-research" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${researchInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${researchInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:researchInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/research/edit.gsp
<%@ page import="com.bits.sart.model.Research" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'research.label', default: 'Research')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-research" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-research" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${researchInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${researchInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:researchInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${researchInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/research/index.gsp
<%@ page import="com.bits.sart.model.Research" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'research.label', default: 'Research')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-research" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-research" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="research.researchCategory.label" default="Research Category" /></th>

                        <g:sortableColumn property="title" title="${message(code: 'research.title.label', default: 'Title')}" />

                        <th><g:message code="research.client.label" default="Client" /></th>

                        <th><g:message code="research.projectManager.label" default="Project Manager" /></th>

                        <g:sortableColumn property="budget" title="${message(code: 'research.budget.label', default: 'Budget')}" />

                        <g:sortableColumn property="methodology" title="${message(code: 'research.methodology.label', default: 'Methodology')}" />

						%{--<g:sortableColumn property="sampleSize" title="${message(code: 'research.sampleSize.label', default: 'Sample Size')}" />--}%

					</tr>
				</thead>
				<tbody>
				<g:each in="${researchInstanceList}" status="i" var="researchInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${researchInstance.id}">${fieldValue(bean: researchInstance, field: "researchCategory")}</g:link></td>

                        <td>${fieldValue(bean: researchInstance, field: "title")}</td>

						<td>${fieldValue(bean: researchInstance, field: "client")}</td>

                        <td>${fieldValue(bean: researchInstance, field: "projectManager")}</td>

                        <td>${fieldValue(bean: researchInstance, field: "budget")}</td>

                        <td>${fieldValue(bean: researchInstance, field: "methodology")}</td>

                        %{--<td>${fieldValue(bean: researchInstance, field: "sampleSize")}</td>--}%

					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${researchInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/research/search.gsp
<%--
  Created by IntelliJ IDEA.
  User: biniam
  Date: 4/3/2014
  Time: 5:35 PM
--%>
<%@ page import="com.bits.sart.model.Research" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'research.label', default: 'Research')}" />
    <title><g:message code="default.search.label" args="[entityName]" /> </title>
</head>

<body>
    <a href="#search-research" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
    <div class="nav" role="navigation">
        <ul>
            <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
            <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
        </ul>
    </div>
    <div id=""search-research" class="content scaffold-search" role="main">
        <h1><g:message code="default.search.label" args="[entityName]" /> </h1>

        <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
        </g:if>

        <g:form action="search">
            <div class="search">
                <div class="researchTitle">
                    <label for="researchTitle">
                        <g:message code="research.search.title" default="Research Title" />
                    </label>
                    <g:textField name="researchTitle"/>
                </div>

                <div class="researchCategory">
                    <label for="researchCategory">
                        <g:message code="research.search.category" default="Research Category" />
                    </label>
                    <g:select name="researchCategory" from="${com.bits.sart.model.ResearchCategory.list()}" optionKey="id" optionValue="name" required="" class="many-to-one" />
                </div>

                <div class="buttons">
                    <g:submitButton name="searchButton"><g:message code="research.search.button" default="Search" /> </g:submitButton>
                </div>
            </div>
        </g:form>

        <table>
            <thead>
            <tr>

                <th><g:message code="research.researchCategory.label" default="Research Category" /></th>

                <g:sortableColumn property="title" title="${message(code: 'research.title.label', default: 'Title')}" />

                <th><g:message code="research.client.label" default="Client" /></th>

                <th><g:message code="research.projectManager.label" default="Project Manager" /></th>

                <g:sortableColumn property="budget" title="${message(code: 'research.budget.label', default: 'Budget')}" />

                <g:sortableColumn property="methodology" title="${message(code: 'research.methodology.label', default: 'Methodology')}" />

            </tr>
            </thead>
            <tbody>
                <g:each in="${searchResults}" status="i" var="searchResult">
                    <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                        <td><g:link action="show" id="${searchResult.id}">${fieldValue(bean: searchResult, field: "researchCategory")}</g:link></td>

                        <td>${fieldValue(bean: searchResult, field: "title")}</td>

                        <td>${fieldValue(bean: searchResult, field: "client")}</td>

                        <td>${fieldValue(bean: searchResult, field: "projectManager")}</td>

                        <td>${fieldValue(bean: searchResult, field: "budget")}</td>

                        <td>${fieldValue(bean: searchResult, field: "methodology")}</td>

                    </tr>
                </g:each>
            </tbody>
        </table>

        <div class="pagination">
            <g:paginate total="${researchInstanceCount ?: 0}" />
        </div>

    </div>

</body>
</html>