grails-app/domain/com/bits/sart/model/SartUser.groovy
package com.bits.sart.model

class SartUser extends User {

	String firstName
	String middleName
	String lastName
	
	String summary
	String position							//	{can be Enum}
	
	GenderTypeEnum gender
	Address address
	
	LevelOfEducation highestLevelOfEducation
	Double yearsOfExperience

    Attachment attachment

	Date dateCreated
	Date lastUpdated
	User createdByUser
	User updatedByUser

	//static hasMany = [attachments : Attachment]
	
	static constraints = {

        firstName blank: false
        middleName blank: false
        lastName blank: false

        summary blank: true
        position blank: false

        gender nullable: true
        address nullable: true

        highestLevelOfEducation nullable: true
        yearsOfExperience nullable: true

        attachment nullable: true
        //attachments nullable: true

		createdByUser nullable:true
		updatedByUser nullable:true
	}
	
}

grails-app/controllers/com/bits/sart/model/SartUserController.groovy
package com.bits.sart.model


import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class SartUserController {

    def userService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond SartUser.list(params), model: [sartUserInstanceCount: SartUser.count()]
    }

    def show(SartUser sartUserInstance) {
        respond sartUserInstance
    }

    def create() {
        respond new SartUser(params)
    }

    @Transactional
    def save(SartUser sartUserInstance) {
        if (sartUserInstance == null) {
            notFound()
            return
        }

        if (sartUserInstance.hasErrors()) {
            respond sartUserInstance.errors, view: 'create'
            return
        }

        sartUserInstance.save flush: true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'sartUserInstance.label', default: 'SartUser'), sartUserInstance.id])
                redirect sartUserInstance
            }
            '*' { respond sartUserInstance, [status: CREATED] }
        }
    }

    @Transactional
    def saveSartUser() {

        File attachedFile = request.getFile('attachmentFileName')

        SartUser user = userService.saveUser(params.username, params.password, params.confirmedPassword, params.firstName, params.middleName, params.lastName, params.gender,
                params.summary, params.position, params.phoneNumber, params.email, params.street, params.woreda,
                params.cityId.toInteger(), params.highestLevelOfEducation, params.yearsOfExperience.toDouble(), params.attachmentDescription,
                params.attachmentType, attachedFile)

        if(null != user) {

            flash.message = message(code: 'user.saveUser.success.result')
            redirect action: 'index'

        } else {

            flash.message = message(code: 'user.saveUser.failed.result', default: 'Error creating User')
            redirect action: 'index'
        }
    }

    def edit(SartUser sartUserInstance) {
        respond sartUserInstance
    }

    @Transactional
    def update(SartUser sartUserInstance) {
        if (sartUserInstance == null) {
            notFound()
            return
        }

        if (sartUserInstance.hasErrors()) {
            respond sartUserInstance.errors, view: 'edit'
            return
        }

        sartUserInstance.save flush: true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'SartUser.label', default: 'SartUser'), sartUserInstance.id])
                redirect sartUserInstance
            }
            '*' { respond sartUserInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(SartUser sartUserInstance) {

        if (sartUserInstance == null) {
            notFound()
            return
        }

        sartUserInstance.delete flush: true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'SartUser.label', default: 'SartUser'), sartUserInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'sartUserInstance.label', default: 'SartUser'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/sartUser/_form.gsp
<%@ page import="com.bits.sart.model.SartUser" %>
%{--<r:require modules="bootstrap-file-upload"/>--}%
%{--
<div style="max-width:500px; border:2px solid #ccc;">
--}%

    <div class="fieldcontain ${hasErrors(bean: sartUserInstance, field: 'username', 'error')} required">
	    <label for="username">
		    <g:message code="sartUser.username.label" default="Username" />
		    <span class="required-indicator">*</span>
	    </label>
	    <g:textField name="username" required="" value="${sartUserInstance?.username}"/>
    </div>

    <div class="fieldcontain ${hasErrors(bean: sartUserInstance, field: 'password', 'error')} required">
        <label for="password">
            <g:message code="sartUser.password.label" default="Password" />
            <span class="required-indicator">*</span>
        </label>
        <g:passwordField name="password" required="" value=""/>
    </div>

    <div class="fieldcontain ${hasErrors(bean: sartUserInstance, field: 'password', 'error')} required">
        <label for="confirmedPassword">
            <g:message code="sartUser.confirm.password.label" default="Confirm Password" />
            <span class="required-indicator">*</span>
        </label>
        <g:passwordField name="confirmedPassword" required="" value=""/>
    </div>

<div class="fieldcontain ${hasErrors(bean: sartUserInstance, field: 'firstName', 'error')} required">
	<label for="firstName">
		<g:message code="sartUser.firstName.label" default="First Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="firstName" required="" value="${sartUserInstance?.firstName}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: sartUserInstance, field: 'middleName', 'error')} required">
	<label for="middleName">
		<g:message code="sartUser.middleName.label" default="Middle Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="middleName" required="" value="${sartUserInstance?.middleName}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: sartUserInstance, field: 'lastName', 'error')} required">
	<label for="lastName">
		<g:message code="sartUser.lastName.label" default="Last Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="lastName" required="" value="${sartUserInstance?.lastName}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: sartUserInstance, field: 'gender', 'error')} ">
    <label for="gender">
        <g:message code="sartUser.gender.label" default="Gender" />

    </label>
    <g:select name="gender" from="${com.bits.sart.model.GenderTypeEnum?.values()}" keys="${com.bits.sart.model.GenderTypeEnum.values()}"
              value="${sartUserInstance?.gender?.name().toString()}" noSelection="['': '--Choose--']" valueMessagePrefix="gender"/>
</div>

<div class="fieldcontain ${hasErrors(bean: sartUserInstance, field: 'summary', 'error')} ">
	<label for="summary">
		<g:message code="sartUser.summary.label" default="Summary" />
        <span class="required-indicator">*</span>
	</label>
	<g:textField name="summary" value="${sartUserInstance?.summary}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: sartUserInstance, field: 'position', 'error')} required">
	<label for="position">
		<g:message code="sartUser.position.label" default="Position" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="position" required="" value="${sartUserInstance?.position}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: sartUserInstance.address, field: 'phoneNumber', 'error')} ">
    <label for="phoneNumber">
        <g:message code="sartUser.address.phoneNumber.label" default="Phone Number" />

    </label>
    <g:textField name="phoneNumber" value="${sartUserInstance?.address?.phoneNumber}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: sartUserInstance.address, field: 'email', 'error')} ">
	<label for="email">
		<g:message code="sartUser.address.email.label" default="Email" />
		
	</label>
	<g:textField name="email" value="${sartUserInstance?.address?.email}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: sartUserInstance, field: 'address', 'error')} required">
    <label for="street">
        <g:message code="sartUser.address.street.label" default="Street" />
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="street" maxlength="100" required="" value="${sartUserInstance?.address?.street}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: sartUserInstance.address, field: 'woreda', 'error')} ">
    <label for="woreda">
        <g:message code="sartUser.address.woreda.label" default="Woreda" />
    </label>
    <g:textField name="woreda" value="${sartUserInstance?.address?.woreda}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: sartUserInstance.address, field: 'city', 'error')} ">
    <label for="cityId">
        <g:message code="sartUser.address.city.label" default="City" />
    </label>
    <g:select id="cityId" name="cityId" from="${com.bits.sart.model.City.list()}" optionKey="id" optionValue="name"
              value="${sartUserInstance?.address?.city?.name}" class="many-to-one" noSelection="['null': '']"/>
</div>


<div class="fieldcontain ${hasErrors(bean: sartUserInstance, field: 'highestLevelOfEducation', 'error')} ">
	<label for="highestLevelOfEducation">
		<g:message code="sartUser.highestLevelOfEducation.label" default="Highest Level Of Education" />
		
	</label>
	<g:select name="highestLevelOfEducation" from="${com.bits.sart.model.LevelOfEducation?.values()}" keys="${com.bits.sart.model.LevelOfEducation.values()}"
              value="${sartUserInstance?.highestLevelOfEducation?.name()}" noSelection="['': '--Choose--']" valueMessagePrefix="levelOfEducation"/>
</div>

<div class="fieldcontain ${hasErrors(bean: sartUserInstance, field: 'yearsOfExperience', 'error')} ">
	<label for="yearsOfExperience">
		<g:message code="sartUser.yearsOfExperience.label" default="Years Of Experience" />
		
	</label>
	<g:field type="number" name="yearsOfExperience" value="${fieldValue(bean: sartUserInstance, field: 'yearsOfExperience')}"/>
</div>

<g:render template="/attachment/form"/>

%{--<div class="fieldcontain ${hasErrors(bean: sartUserInstance.attachments, field: 'fileName', 'error')} required">
    <label for="attachmentFileName">
        <g:message code="attachment.fileName.label" default="File Name" />
        <span class="required-indicator">*</span>
    </label>
    <bsfu:fileUpload action="uploadAttachment" controller="attachment"/>
</div>--}%

grails-app/views/sartUser/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'sartUser.label', default: 'SartUser')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-sartUser" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-sartUser" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${sartUserInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${sartUserInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:sartUserInstance, action:'saveSartUser']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/sartUser/edit.gsp
<%@ page import="com.bits.sart.model.SartUser" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'sartUser.label', default: 'SartUser')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-sartUser" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-sartUser" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${sartUserInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${sartUserInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:sartUserInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${sartUserInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/sartUser/index.gsp
<%@ page import="com.bits.sart.model.SartUser" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'sartUser.label', default: 'SartUser')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-sartUser" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-sartUser" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="username" title="${message(code: 'sartUser.username.label', default: 'Username')}" />

						<g:sortableColumn property="firstName" title="${message(code: 'sartUser.firstName.label', default: 'First Name')}" />
					
						<g:sortableColumn property="middleName" title="${message(code: 'sartUser.middleName.label', default: 'Middle Name')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${sartUserInstanceList}" status="i" var="sartUserInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${sartUserInstance.id}">${fieldValue(bean: sartUserInstance, field: "username")}</g:link></td>

						<td>${fieldValue(bean: sartUserInstance, field: "firstName")}</td>
					
						<td>${fieldValue(bean: sartUserInstance, field: "middleName")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${sartUserInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/sartUser/show.gsp
<%@ page import="com.bits.sart.model.SartUser" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'sartUser.label', default: 'SartUser')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-sartUser" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-sartUser" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list sartUser">
			
				<g:if test="${sartUserInstance?.username}">
				<li class="fieldcontain">
					<span id="username-label" class="property-label"><g:message code="sartUser.username.label" default="Username" /></span>
					
						<span class="property-value" aria-labelledby="username-label"><g:fieldValue bean="${sartUserInstance}" field="username"/></span>
					
				</li>
				</g:if>

				<g:if test="${sartUserInstance?.firstName}">
				<li class="fieldcontain">
					<span id="firstName-label" class="property-label"><g:message code="sartUser.firstName.label" default="First Name" /></span>
					
						<span class="property-value" aria-labelledby="firstName-label"><g:fieldValue bean="${sartUserInstance}" field="firstName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${sartUserInstance?.middleName}">
				<li class="fieldcontain">
					<span id="middleName-label" class="property-label"><g:message code="sartUser.middleName.label" default="Middle Name" /></span>
					
						<span class="property-value" aria-labelledby="middleName-label"><g:fieldValue bean="${sartUserInstance}" field="middleName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${sartUserInstance?.lastName}">
				<li class="fieldcontain">
					<span id="lastName-label" class="property-label"><g:message code="sartUser.lastName.label" default="Last Name" /></span>
					
						<span class="property-value" aria-labelledby="lastName-label"><g:fieldValue bean="${sartUserInstance}" field="lastName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${sartUserInstance?.summary}">
				<li class="fieldcontain">
					<span id="summary-label" class="property-label"><g:message code="sartUser.summary.label" default="Summary" /></span>
					
						<span class="property-value" aria-labelledby="summary-label"><g:fieldValue bean="${sartUserInstance}" field="summary"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${sartUserInstance?.position}">
				<li class="fieldcontain">
					<span id="position-label" class="property-label"><g:message code="sartUser.position.label" default="Position" /></span>
					
						<span class="property-value" aria-labelledby="position-label"><g:fieldValue bean="${sartUserInstance}" field="position"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${sartUserInstance?.gender}">
				<li class="fieldcontain">
					<span id="gender-label" class="property-label"><g:message code="sartUser.gender.label" default="Gender" /></span>
					
						<span class="property-value" aria-labelledby="gender-label"><g:fieldValue bean="${sartUserInstance}" field="gender"/></span>
					
				</li>
				</g:if>

                <g:if test="${sartUserInstance?.address?.street}">
                    <li class="fieldcontain">
                        <span id="street-label" class="property-label"><g:message code="address.street.label" default="Street" /></span>

                        <span class="property-value" aria-labelledby="street-label"><g:fieldValue bean="${sartUserInstance?.address}" field="street"/></span>

                    </li>
                </g:if>

                <g:if test="${sartUserInstance?.address?.woreda}">
                    <li class="fieldcontain">
                        <span id="woreda-label" class="property-label"><g:message code="address.woreda.label" default="Woreda" /></span>

                        <span class="property-value" aria-labelledby="woreda-label"><g:fieldValue bean="${sartUserInstance?.address}" field="woreda"/></span>

                    </li>
                </g:if>

                <g:if test="${sartUserInstance?.address?.phoneNumber}">
                    <li class="fieldcontain">
                        <span id="phoneNumber-label" class="property-label"><g:message code="address.phoneNumber.label" default="Phone Number" /></span>

                        <span class="property-value" aria-labelledby="phoneNumber-label"><g:fieldValue bean="${sartUserInstance?.address}" field="phoneNumber"/></span>

                    </li>
                </g:if>

                <g:if test="${sartUserInstance?.address?.email}">
                    <li class="fieldcontain">
                        <span id="email-label" class="property-label"><g:message code="address.email.label" default="Email" /></span>

                        <span class="property-value" aria-labelledby="email-label"><g:fieldValue bean="${sartUserInstance?.address}" field="email"/></span>

                    </li>
                </g:if>

                <g:if test="${sartUserInstance?.address?.city}">
                    <li class="fieldcontain">
                        <span id="city-label" class="property-label"><g:message code="address.city.label" default="City" /></span>

                        <span class="property-value" aria-labelledby="city-label"><g:link controller="city" action="show" id="${sartUserInstance?.address?.city?.id}">${sartUserInstance?.address?.city?.encodeAsHTML()}</g:link></span>

                    </li>
                </g:if>

                <g:if test="${sartUserInstance?.highestLevelOfEducation}">
				<li class="fieldcontain">
					<span id="highestLevelOfEducation-label" class="property-label"><g:message code="sartUser.highestLevelOfEducation.label" default="Highest Level Of Education" /></span>
					
						<span class="property-value" aria-labelledby="highestLevelOfEducation-label"><g:fieldValue bean="${sartUserInstance}" field="highestLevelOfEducation"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${sartUserInstance?.yearsOfExperience}">
				<li class="fieldcontain">
					<span id="yearsOfExperience-label" class="property-label"><g:message code="sartUser.yearsOfExperience.label" default="Years Of Experience" /></span>
					
						<span class="property-value" aria-labelledby="yearsOfExperience-label"><g:fieldValue bean="${sartUserInstance}" field="yearsOfExperience"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${sartUserInstance?.accountExpired}">
				<li class="fieldcontain">
					<span id="accountExpired-label" class="property-label"><g:message code="sartUser.accountExpired.label" default="Account Expired" /></span>
					
						<span class="property-value" aria-labelledby="accountExpired-label"><g:formatBoolean boolean="${sartUserInstance?.accountExpired}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${sartUserInstance?.accountLocked}">
				<li class="fieldcontain">
					<span id="accountLocked-label" class="property-label"><g:message code="sartUser.accountLocked.label" default="Account Locked" /></span>
					
						<span class="property-value" aria-labelledby="accountLocked-label"><g:formatBoolean boolean="${sartUserInstance?.accountLocked}" /></span>
					
				</li>
				</g:if>

                <g:if test="${sartUserInstance?.attachments?.description}">
                    <li class="fieldcontain">
                        <span id="description-label" class="property-label"><g:message code="attachment.description.label" default="Description" /></span>

                        <span class="property-value" aria-labelledby="description-label"><g:fieldValue bean="${sartUserInstance?.attachments}" field="description"/></span>

                    </li>
                </g:if>

                <g:if test="${sartUserInstance?.attachments?.fileName}">
                    <li class="fieldcontain">
                        <span id="fileName-label" class="property-label"><g:message code="attachment.fileName.label" default="File Name" /></span>

                    </li>
                </g:if>

                <g:if test="${sartUserInstance?.attachments?.type}">
                    <li class="fieldcontain">
                        <span id="type-label" class="property-label"><g:message code="attachment.type.label" default="Type" /></span>

                        <span class="property-value" aria-labelledby="type-label"><g:fieldValue bean="${sartUserInstance?.attachments}" field="type"/></span>

                    </li>
                </g:if>

				<g:if test="${sartUserInstance?.enabled}">
				<li class="fieldcontain">
					<span id="enabled-label" class="property-label"><g:message code="sartUser.enabled.label" default="Enabled" /></span>
					
						<span class="property-value" aria-labelledby="enabled-label"><g:formatBoolean boolean="${sartUserInstance?.enabled}" /></span>
					
				</li>
				</g:if>

				<g:if test="${sartUserInstance?.passwordExpired}">
				<li class="fieldcontain">
					<span id="passwordExpired-label" class="property-label"><g:message code="sartUser.passwordExpired.label" default="Password Expired" /></span>
					
						<span class="property-value" aria-labelledby="passwordExpired-label"><g:formatBoolean boolean="${sartUserInstance?.passwordExpired}" /></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:sartUserInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${sartUserInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>