grails-app/domain/com/bits/sart/model/Client.groovy
package com.bits.sart.model

class Client extends AbstractDomain {

	String name
	
	Address address		//{do we need this?}
	
	Date dateCreated
	Date lastUpdated
	User createdByUser
	User updatedByUser
	
	//static belongsTo = [research : Research]
	
	static constraints = {

        name unique: true, blank: false
		address nullable:true
		
		createdByUser nullable:true
		updatedByUser nullable:true
	}
	
}

grails-app/controllers/com/bits/sart/model/ClientController.groovy
package com.bits.sart.model


import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class ClientController {

    def clientService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Client.list(params), model: [clientInstanceCount: Client.count()]
    }

    def show(Client clientInstance) {
        respond clientInstance
    }

    def create() {
        respond new Client(params)
    }

    @Transactional
    def save(Client clientInstance) {
        if (clientInstance == null) {
            notFound()
            return
        }

        if (clientInstance.hasErrors()) {
            respond clientInstance.errors, view: 'create'
            return
        }

        clientInstance.save flush: true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'clientInstance.label', default: 'Client'), clientInstance.id])
                redirect clientInstance
            }
            '*' { respond clientInstance, [status: CREATED] }
        }
    }

    @Transactional
    def saveClient() {

        Client client = clientService.saveClient(params.clientName, params.street, params.woreda, params.phoneNumber, params.cityId.toInteger())

        if(null != client) {

            flash.message = message(code: 'client.saveClient.success.result')
            redirect action: 'index'
        } else {

            flash.message = message(code: 'client.saveClient.failed.result', default: 'Error creating Client')
            redirect action: 'index'
        }
    }

    def edit(Client clientInstance) {
        respond clientInstance
    }

    @Transactional
    def update(Client clientInstance) {
        if (clientInstance == null) {
            notFound()
            return
        }

        if (clientInstance.hasErrors()) {
            respond clientInstance.errors, view: 'edit'
            return
        }

        clientInstance.save flush: true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Client.label', default: 'Client'), clientInstance.id])
                redirect clientInstance
            }
            '*' { respond clientInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Client clientInstance) {

        if (clientInstance == null) {
            notFound()
            return
        }

        clientInstance.delete flush: true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Client.label', default: 'Client'), clientInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'clientInstance.label', default: 'Client'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/client/_form.gsp
<%@ page import="com.bits.sart.model.Client" %>

<div class="fieldcontain ${hasErrors(bean: clientInstance, field: 'clientName', 'error')} required">
	<label for="clientName">
		<g:message code="client.name.label" default="Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="clientName" required="" value="${clientInstance?.name}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: clientInstance, field: 'address', 'error')} required">
    <label for="street">
        <g:message code="client.address.street.label" default="Street" />
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="street" maxlength="100" required="" value="${clientInstance?.address?.street}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: clientInstance.address, field: 'woreda', 'error')} ">
    <label for="woreda">
        <g:message code="client.address.woreda.label" default="Woreda" />
    </label>
    <g:textField name="woreda" value="${clientInstance?.address?.woreda}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: clientInstance.address, field: 'phoneNumber', 'error')} ">
    <label for="phoneNumber">
        <g:message code="client.address.phoneNumber.label" default="Phone Number" />

    </label>
    <g:textField name="phoneNumber" value="${clientInstance?.address?.phoneNumber}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: clientInstance.address, field: 'email', 'error')} ">
    <label for="email">
        <g:message code="client.address.email.label" default="Email" />

    </label>
    <g:textField name="email" value="${clientInstance?.address?.email}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: clientInstance.address, field: 'city', 'error')} ">
    <label for="cityId">
        <g:message code="client.address.city.label" default="City" />
    </label>
    <g:select id="cityId" name="cityId" from="${com.bits.sart.model.City.list()}" optionKey="id" optionValue="name" value="${clientInstance?.address?.city?.name}" class="many-to-one" noSelection="['null': '']"/>
</div>

grails-app/views/client/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'client.label', default: 'Client')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-client" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-client" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${clientInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${clientInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:clientInstance, action:'saveClient']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/client/edit.gsp
<%@ page import="com.bits.sart.model.Client" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'client.label', default: 'Client')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-client" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-client" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${clientInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${clientInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:clientInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${clientInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/client/index.gsp
<%@ page import="com.bits.sart.model.Client" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'client.label', default: 'Client')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-client" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-client" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="name" title="${message(code: 'client.name.label', default: 'Name')}" />

                        <g:sortableColumn property="address.street" title="${message(code: 'client.address.street.label', default: 'Street')}" />

                        <g:sortableColumn property="address.woreda" title="${message(code: 'client.address.woreda.label', default: 'Woreda')}" />

                        <g:sortableColumn property="address.phoneNumber" title="${message(code: 'client.address.phoneNumber.label', default: 'Phone Number')}" />

                        <g:sortableColumn property="address.city" title="${message(code: 'client.address.city.label', default: 'City')}" />

					</tr>
				</thead>
				<tbody>
				<g:each in="${clientInstanceList}" status="i" var="clientInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${clientInstance.id}">${fieldValue(bean: clientInstance, field: "name")}</g:link></td>
					
						<td>${fieldValue(bean: clientInstance, field: "address.street")}</td>

                        <td>${fieldValue(bean: clientInstance, field: "address.woreda")}</td>

                        <td>${fieldValue(bean: clientInstance, field: "address.phoneNumber")}</td>

                        <td>${fieldValue(bean: clientInstance, field: "address.city.name")}</td>

					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${clientInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/client/show.gsp
<%@ page import="com.bits.sart.model.Client" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'client.label', default: 'Client')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-client" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-client" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list client">
			
				<g:if test="${clientInstance?.name}">
				<li class="fieldcontain">
					<span id="name-label" class="property-label"><g:message code="client.name.label" default="Name" /></span>
					
						<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${clientInstance}" field="name"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${clientInstance?.address.street}">
				<li class="fieldcontain">
					<span id="address.street-label" class="property-label">
                        <g:message code="client.address.street.label" default="Street" />
                    </span>
					
					<span class="property-value" aria-labelledby="address.street-label">
                        <g:fieldValue bean="${clientInstance.address}" field="street"/>
                    </span>
				</li>
				</g:if>

                <g:if test="${clientInstance?.address.woreda}">
                    <li class="fieldcontain">
                        <span id="address.woreda-label" class="property-label">
                            <g:message code="client.address.woreda.label" default="Woreda" />
                        </span>

                        <span class="property-value" aria-labelledby="address.woreda-label">
                            <g:fieldValue bean="${clientInstance.address}" field="woreda"/>
                        </span>
                    </li>
                </g:if>

                <g:if test="${clientInstance?.address.phoneNumber}">
                    <li class="fieldcontain">
                        <span id="address.phoneNumber-label" class="property-label">
                            <g:message code="client.address.phoneNumber.label" default="Phone Number" />
                        </span>

                        <span class="property-value" aria-labelledby="address.phoneNumber-label">
                            <g:fieldValue bean="${clientInstance.address}" field="phoneNumber"/>
                        </span>
                    </li>
                </g:if>

                <g:if test="${clientInstance?.address.city}">
                    <li class="fieldcontain">
                        <span id="address.city-label" class="property-label">
                            <g:message code="client.address.city.label" default="City" />
                        </span>

                        <span class="property-value" aria-labelledby="address.city-label">
                            <g:fieldValue bean="${clientInstance.address.city}" field="name"/>
                        </span>
                    </li>
                </g:if>
			</ol>
			<g:form url="[resource:clientInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${clientInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>